version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.6.1
    environment:
      - cluster.name=stocks-api
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  api:
    image: elastic-search-api
    build: .
    ports:
      - "3000:3000"
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
