version: '3'

services:
  elasticsearch-cluster:
    container_name: elasticsearch-cluster
    image: elasticsearch:7.2.0
    environment:
      - cluster.name=elasticsearch-api
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch-network

  elasticsearch-api:
    build: .
    container_name: elasticsearch-api
    volumes:
      - ./:/usr/src/app
    tty: true
    depends_on:
      - elasticsearch-cluster
    networks:
      - elasticsearch-network
    links:
      - elasticsearch-cluster
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      - ES_HOST=http://elasticsearch-cluster:9200/

volumes:
  data:
    driver: local

networks:
  elasticsearch-network:
    driver: bridge
